name = "apllec"
description = "Apllec Zola theme for the apllec blog."
license = "MIT"
homepage = "https://github.com/apllec/apllec-theme"
min_version = "0.15.0"

[extra]

[author]
name = "Aaran Xu"
homepage = "https://github.com/aaranxu"

[original]
author = "h-enk"
homepage = "https://getdoks.org/"
repo = "https://github.com/h-enk/doks"
